openapi: 3.0.0
info:
  title: GlobalPay API
  version: 1.0.0
paths:
  /api/customers:
    get:
      summary: List customers
      responses:
        '200':
          description: A list of customers
    post:
      summary: Create customer
      responses:
        '200':
          description: Customer created
  /api/payments:
    post:
      summary: Create payment intent
      responses:
        '200':
          description: Payment intent created
  /api/payments/{id}/confirm:
    post:
      summary: Confirm payment
      responses:
        '200':
          description: Payment confirmed
  /api/payments/{id}/refund:
    post:
      summary: Refund payment
      responses:
        '200':
          description: Payment refunded
